spring:
  application:
    name: app-one
server:
  port: 9704
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 2 #心跳间隔时间,默认是30秒
    lease-expiration-duration-in-seconds: 6 #最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了，默认是90秒
app:
  build:
    name: app-one